
name: linter

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - name: git clone
        uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.21'
      - run: go version

      - name: Run Linter
        run: make lint
